#!/bin/sh
#
# Download the glidein files we need to create pilot jobs and
# put them in subdirectories of /var/spool/dune-vpf/glidein
#
# This is only needed for creating extra entries or making
# local modifications of them
#

rm -Rf /var/spool/dune-vpf/glidein

mkdir -p /var/spool/dune-vpf/glidein/scripts

curl https://raw.githubusercontent.com/glideinWMS/glideinwms/master/tools/manual_glidein_startup \
  > /var/spool/dune-vpf/glidein/scripts/manual_glidein_startup

curl https://raw.githubusercontent.com/glideinWMS/glideinwms/master/creation/web_base/glidein_startup.sh \
  > /var/spool/dune-vpf/glidein/scripts/glidein_startup.sh

chmod +x /var/spool/dune-vpf/glidein/scripts/*
  
(

cat <<EOF
web http://gfactory-2.opensciencegrid.org/factory/stage j81aAK
web/entry_UBoone_T2_UK_Manchester_ce02 http://gfactory-2.opensciencegrid.org/factory/stage/entry_UBoone_T2_UK_Manchester_ce02 j81aAK
clientweb http://gpfrontend01.fnal.gov:8319/vofrontend/stage j819gN
clientwebgroup http://gpfrontend01.fnal.gov:8319/vofrontend/stage/group_dune_cern j819gN
EOF

) | (

while read path base_url random_code
do

  description_file=description.$random_code.cfg
  mkdir -p /var/spool/dune-vpf/glidein/$path
  cd /var/spool/dune-vpf/glidein/$path

  wget -v $base_url/$description_file

  signature_file=`grep '^signature' $description_file | head -1 | sed 's/^signature[[:space:]]*//'`

  wget -v $base_url/$signature_file

  grep -v '^#' $signature_file | (
                                   while read sig filename
                                   do
                                     wget -v $base_url/$filename
                                   done
                                 )
done

)

