#!/bin/sh
#
# For testing: VPF will create this file on the fly in future
#

WMS_COLLECTOR=gfactory-2.opensciencegrid.org
CLIENT_NAME=fermilab_okd_gpfe01.dune 
REQ_NAME=UBoone_T2_UK_Manchester_ce01@gfactory_instance@OSG

./manual_glidein_startup \
  --wms-collector=$WMS_COLLECTOR \
  --client-name=$CLIENT_NAME \
  --req-name=$REQ_NAME \
  --cmd-out-file=glidein_startup_wrapper \
  --glidein-startup=./glidein_startup.sh 

cat <<EOF >vpf.xrsl
&( executable = "vpf_pilot" )( jobname = "vpf_test" )( stdout = "stdout" )( join = "yes" )( gmlog = "gmlog" )(inputFiles = ("glidein_startup_wrapper" "")("vpf_pilot" "")("user.proxy" "")("glidein_startup.sh" ""))
EOF

arcsub --cluster=ce01.tier2.hep.manchester.ac.uk vpf.xrsl 
